name: Upload dotnet package

on:
  release:
    types: [created]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/vbondarev/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release HostedConsoleApplicationProjectTemplate.csproj
      - name: Create the package
        run: dotnet pack --configuration Release HostedConsoleApplicationProjectTemplate.csproj
      - name: Files
      - run: ls
      - name: Publish the package to GPR
        run: dotnet nuget push HostedConsoleApplicationProjectTemplate/bin/Release/*.nupkg